FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY Mirae_Bank_Final_Project .

RUN apt-get update && apt-get install -y maven

RUN mvn clean package

EXPOSE 8082

CMD ["java","-cp","target/classes","com.bank.appEntry.Main"]